language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - ruby-head

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: bundle exec rake spec

notifications:
  email: true

services:
  - mongodb

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
